<%@ Page Title="" Language="C#" MasterPageFile="~/master-all.Master" AutoEventWireup="true" CodeBehind="Privacy_Policy.aspx.cs" Inherits="A2ZGymSolution.Privacy_Policy" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
 <br/>
<div style="width: 800px; margin-left: 0px; margin-right: 0px">
 <h3 style="text-align:center; font-size: 30px; color: #000;">Privacy Policy</h3>
<p>&nbsp;</p>
<p><span style="line-height:1.6em;">By accessing and using (i) the domain name www.A2zgym.com (the “</span><strong style="line-height:1.6em;">Website</strong><span style="line-height:1.6em;">”) and/or (ii) any other software application developed by the Company (as defined below) for use on wireless computing devices such as smartphones and tablets and also for use on desktop or laptop computers ((i) and (ii) hereinafter collectively referred to the “</span><strong style="line-height:1.6em;">Electronic Media</strong><span style="line-height:1.6em;">”), you agree to be bound by the terms of this privacy policy (“</span><strong style="line-height:1.6em;">Policy</strong><span style="line-height:1.6em;">”). This Policy is an electronic record in terms of the Information Technology Act, 2000 and rules made thereunder. Further, this electronic record is generated by a computer system and does not require any physical or digital signatures. This electronic record is published in accordance with the relevant provisions of the Information Technology Act, 2000 and rules made thereunder.</span></p>

<p>&nbsp;</p>

<p>Please note that this Policy is incorporated in and forms a part of the terms of service of the Electronic Media available at <a href="http://fitpass.co.in/terms-and-conditions/">http://www.fitpass.co.in/terms-and-conditions/</a> and the other the guidelines, rules, terms, conditions and/or applicable policies and procedures (“<strong>Company Policies</strong>”) particular to any specific service or products of the Company, which shall be posted on the Electronic Media from time to time.</p>

<p>&nbsp;</p>

<p>&nbsp;</p>

<p><strong>1.&nbsp;What This Policy Covers</strong></p>

<p>&nbsp;</p>

<p><strong>1.1</strong>&nbsp;This Policy governs the Electronic Media and the information practices of and any other online products, services, content or software applications (the “<strong>Services</strong>”) offered by ASR Market Ventures Pvt. Ltd., a private limited company incorporated in accordance with the laws of India, and its parent company, its subsidiaries or its affiliates (hereinafter collectively referred to as the (“<strong>Company</strong>”). By providing personal information through the Electronic Media or any Service, you understand and acknowledge that you are providing such personal information to all entities listed above. Personal information is information about you that is personally identifiable, such as your name, address, email address, phone number and credit / debit card details or any other financial or personal information, etc. that may or may not be otherwise publicly available.</p>

<p>&nbsp;</p>

<p><strong>1.2</strong> This Policy does not apply to the practices of companies that are not owned, controlled, managed or operated by the Company or to persons that the Company does not employ, engage or manage.</p>

<p>&nbsp;</p>

<p><strong>1.3</strong> For the purpose of this Policy, wherever the context so requires, references to “<strong>you</strong>” shall mean the user of the Electronic Media (“<strong>User</strong>”) and references to “<strong>us</strong>” or “<strong>we</strong>” shall mean the Company.</p>

<p>&nbsp;</p>

<p>&nbsp;</p>

<p><strong>2.&nbsp;Information Collection and Use</strong>&nbsp;</p>

<p>&nbsp;</p>

<p><strong>2.1</strong> We collect and store personal information when you sign-in and register with us on the Electronic Media and when you use the Services.</p>

<p>&nbsp;</p>

<p><strong>2.2</strong> When you register with us on the Electronic Media, we may ask for information which is mandatory such as your name, address, email address, phone number, credit / debit card information, business information, franchise and other licence information and other financial information, and certain other information which is optional. Wherever possible, we indicate which information is mandatory and which information is optional for you to share with us. Once you register with us on the Electronic Media and log in to use our Services, you are not anonymous to us.</p>

<p>&nbsp;</p>

<p><strong>2.3</strong> We also collect information about your transactions with other users/member, including information regarding applicable rates for classes, fees structures an schedules.</p>

<p>&nbsp;</p>

<p><strong>2.4</strong> We automatically receive and record information on our server logs regarding your sessions on various Electronic Media and other electronic formats, and (if you have set your computer to receive cookies) related cookie information. For further information, see the section below headed “<strong>Cookies</strong>”.</p>

<p>&nbsp;</p>

<p><strong>2.5</strong> We may use your information for the following general purposes:</p>

<p><strong>(a)</strong> to contact you;</p>

<p><strong>(b)</strong> to facilitate availing and provision of specialised services/ products, expert advice, professional consulting etc. by you through the Company;</p>

<p><strong>(c)</strong> to administer our business and Electronic Media;</p>

<p><strong>(d)</strong> to send invoices, statements, agreements and/or to collect payment from you or make payments to you on behalf of the person/user/member availing specialised services/products (as the case may be);</p>

<p><strong>(e)</strong> to send you marketing related communications;</p>

<p><strong>(f)</strong> &nbsp;to deal with enquiries and complaints raised by you and to troubleshoot problems;</p>

<p><strong>(g)</strong> to prevent the Electronic Media from fraud, errors or any illegal activity;</p>

<p><strong>(h)</strong> to ensure compliance with all applicable laws and to ensure safety of the Electronic Media and all Users;</p>

<p><strong>(i)</strong> to enforce the terms of service of the Electronic Media and other Company Policies;</p>

<p><strong>(j)</strong> &nbsp;to carry out market research and Users’ interest; and</p>

<p><strong>(k)</strong> &nbsp;to customise your experience of use of the Electronic Media.</p>

<p>&nbsp;</p>

<p><strong>2.6</strong> If you post any messages or leave any feedback on the Electronic Media, we may use such information for dispute resolution, troubleshooting problems and provide customer support.&nbsp;</p>

<p>&nbsp;</p>

<p>&nbsp;</p>

<p><strong>3.&nbsp;Information Sharing and Disclosure</strong></p>

<p>&nbsp;</p>

<p><strong>3.1</strong> Some of the pages on the Electronic Media are freely accessible by all Users and require no prior registration. Further, certain other pages on the Electronic Media can be accessed by Users only after entering in their details, username and password. Therefore, we request you to use a safe and secure server to access the Electronic Media to ensure safety of your username, password and other information. We do not guarantee any security or privacy of any information which may be available to all Users and visitors of the Electronic Media publicly. Further, the Electronic Media may contain links to other websites. Please note that we do not endorse any links or websites and are not responsible for the privacy practices of such third party websites.</p>

<p>&nbsp;</p>

<p><strong>3.2</strong> &nbsp;We do not rent, sell, disclose or share personal information about you with other people or non-affiliated companies except to provide products or services you’ve requested. However, you agree that in addition to as may be provided in this Policy, we may also disclose your personal information under the following circumstances:</p>

<p>&nbsp;</p>

<p><strong>(a)</strong>&nbsp;Third party service providers: we employ or might, as per requirement and business needs of the Company, employ, engage, contract with third party service providers to work on behalf of or with us, under agreements containing confidentiality obligations and in accordance with law, in relation to the Services provided by us on the Electronic Media. These third party service providers may use your personal information in assisting us to communicate with you about our offers or for delivery of the vehicles, assisting in payment facilities, providing customer support, assisting in advertising on the Electronic Media, etc. Such third party service providers do not have any independent right to the information provided by us to them;</p>

<p>&nbsp;</p>

<p><strong>(b)</strong>&nbsp;&nbsp;Compliance with laws and protection of Users: we may release your personal information when the same is required in order to comply with the law, in response to court orders, court summons, judgments, decrees, injunctions, arbitral awards, administrative orders, governmental investigation or orders of any government authority or any other legal process, to establish/exercise our legal rights or defend against legal claims or in the event we reasonably believe that doing so is legally required or is in your interest to protect your property or other legal rights or property or rights of others. We may also share your personal information in order to enforce and fully comply with our terms of service and other Company Policies;</p>

<p>&nbsp;</p>

<p><strong>(c)</strong>&nbsp;Business transfer and Mergers: we may transfer your personal information if the Company, is acquired by or merged with another company, to the extent permitted by applicable law and/or required under the scheme/arrangement of merger, etc. In such an event we will notify you before your personal information is transferred/shared with the other entity and hence becomes subject to a different privacy policy;</p>

<p>&nbsp;</p>

<p><strong>(d)</strong>&nbsp;Contracting parties: we transfer/share your information with potential sellers/buyers of products / services, with sellers/buyers of products / services availed/offered/purchased/sold by you and to their respective service providers to facilitate availing/provision of products / service by you or to you in order to consummate the transaction.</p>

<p>&nbsp;</p>

<p><strong>(e)</strong>&nbsp;With your consent: in addition to the aforementioned circumstances, we may share your personal information with third parties with your prior consent and/or at your request.</p>

<p>&nbsp;</p>

<p>&nbsp;</p>

<p><strong>4.&nbsp;Accessing your own personal information</strong></p>

<p>&nbsp;</p>

<p><strong>4.1</strong> Whenever you access the Electronic Media, we aim to provide you with your personal information stored with us. That information may require to be updated from time to time. Therefore, we also strive to give you ways to quickly update any of your personal information. When updating your personal information, we may ask you to verify your identity before we act on your request.</p>

<p>&nbsp;</p>

<p><strong>4.2</strong> Wherever we can provide information and access, we will do so for free except when it would require a disproportionate effort, in which cases we may do so for a reasonable fee to be determined on a case to case basis.</p>

<p>&nbsp;</p>

<p>&nbsp;</p>

<p><strong>5.&nbsp;Cookies</strong></p>

<p>&nbsp;</p>

<p><strong>5.1</strong> We may place text files in the browser files of your computer system. A cookie itself does not contain personal information and it will only enable us to relate your use of the Company’s Electronic Media and/or Services and your behaviour on the Electronic Media to information that you have specifically and knowingly provided. The only personal information that a cookie can contain is the information you yourself supply to the cookie. A cookie can’t read data off your hard disk or read cookie files created by other websites.</p>

<p>&nbsp;</p>

<p><strong>5.2</strong> We use cookies to track User traffic patterns on the Electronic Media and their use of the Services. We do not use cookies to track your use of third party websites, applications or software. Please also note that we do not control use of cookies by any third party.</p>

<p>&nbsp;</p>

<p><strong>5.3</strong> We may place both permanent and temporary cookies. A permanent cookie will remain on your web browser until its expiry date, unless deleted prior to such expiry date. However, most cookies are “<strong>session cookies</strong>” meaning that they automatically get deleted from your computer system at the end of the session. You can refuse cookies by turning them off in your browser or alternatively you can also set your browser to warn you before accepting any cookies. Therefore, you are always free to decline our cookies if your browser permits, however:</p>

<p>&nbsp;</p>

<p><strong>(i)</strong> we use certain encrypted cookies to authenticate the User on each page after the User logs on to the Electronic Media or accesses any Services. You will not be entitled to log in to the members’ area of the Electronic Media without accepting such cookies; and</p>

<p>&nbsp;</p>

<p><strong>(ii)</strong> accepting the encrypted or the log-in cookies will only enable you to access the members’ area of the Electronic Media or the Services.</p>

<p>&nbsp;</p>

<p>Please note that some other features and services (such as creating customised searches for vehicles) may still not function properly or conveniently on your computer system if the other cookies placed by us on your hard drive are disabled.</p>

<p>&nbsp;</p>

<p>&nbsp;</p>

<p><strong>6.&nbsp;Communications</strong></p>

<p>&nbsp;</p>

<p><strong>6.1</strong> We reserve the right to send you certain communications relating to the Electronic Media, the Services and your account with us, including but not limited to notifications, service announcements, administrative messages without offering you the opportunity to opt-out of receiving them (although we will obtain your consent at the time you create your account). Should you choose not to receive such communications, your continued and unrestricted access to the Electronic Media and all Services may be affected.</p>

<p>&nbsp;</p>

<p>&nbsp;</p>

<p><strong>7.&nbsp;Data Storage</strong></p>

<p>&nbsp;</p>

<p><strong>7.1</strong> &nbsp;We may store your account information in our databases indefinitely following the termination of your account with us to the maximum extent permitted by law.&nbsp;&nbsp;</p>

<p>&nbsp;</p>

<p>&nbsp;</p>

<p><strong>8. Confidentiality and Security</strong>&nbsp;</p>

<p>&nbsp;</p>

<p><strong>8.1</strong> We limit access to personal information about you to such persons who we believe reasonably need to come into contact with that information to provide services to you or in order to do their jobs.</p>

<p>&nbsp;</p>

<p><strong>8.2</strong> We have physical, electronic, and procedural safeguards that comply with our legal responsibilities to protect personal information about you.</p>

<p>&nbsp;</p>

<p><strong>8.3</strong>&nbsp;If we learn of a security systems breach we may attempt to notify you electronically so that you can take appropriate protective steps. By using the Electronic Media or Services or providing personal information to us you agree that we can communicate with you electronically regarding security, privacy and administrative issues relating to you and your use of the Electronic Media or Services. Further, we may also post a notice on our Electronic Media pertaining to the security system breach in order to notify all the Users at large. We may also send an email to you at the email address you have provided to us in these circumstances and if required by law, you may have a legal right to receive notice of a security breach in writing.</p>

<p>&nbsp;</p>

<p><strong>8.4 </strong>We take your security seriously and take reasonable steps to protect your information. No data transmission over the internet or information storage technology can be guaranteed to be absolutely secure. The following is a summary of the measures we take to protect your information and descriptions of the procedures we implement for different types of information you may provide to us:</p>

<p>&nbsp;</p>

<p><strong>(i)</strong> Payment information: We use third party service providers (payment gateways) and do not store any payment data on our servers.</p>

<p>&nbsp;</p>

<p><strong>(ii)</strong>&nbsp;Third party service providers and suppliers: We work with third party service providers/experts/trainers/professional, suppliers who provide services on our behalf or to us to us. We enter into agreements with such third party service providers, experts, trainers, professional and suppliers to ensure complete security and safety of the User information. Such third party service providers do not have any independent right to the information provided by us to them.</p>

<p>&nbsp;</p>

<p><strong>(iii)&nbsp;</strong>Employee and contractor access to information: We limit access to personal information about you to those employees and contractors who we reasonably believe need to come into contact with that information to provide products or services to you or in order to do their jobs.&nbsp;</p>

<p>&nbsp;</p>

<p><strong>(iv)</strong> Education and training for employees: We have implemented a company-wide education and training program about security that is required of every employee of the Company.</p>

<p>&nbsp;</p>

<p>&nbsp;</p>

<p><strong>9.&nbsp;Changes to this Privacy Policy</strong></p>

<p><strong>9.1 &nbsp;</strong>We may update, revise or amend this Policy from time to time without any prior notice to you. When we revise, update or amend this Policy, we also revise the date at the start of the Policy. For changes to this Policy that may be materially less restrictive on our use or disclosure of your personal information provided to us, we will attempt to obtain your consent before implementing the change. We encourage you to periodically review this Policy to stay informed about how we are protecting the information we collect. Your continued use of Electronic Media constitutes your agreement to this Policy and any updates from time to time.</p>

<p>&nbsp;</p>

<p>&nbsp;</p>

<p><strong>10.&nbsp;Grievance Officer</strong></p>

<p><strong>10.1 </strong>&nbsp;In accordance with the provisions of the Information Technology Act, 2000 and rules made thereunder, the name and contact details of the grievance officer are provided below:</p>

<p>&nbsp;</p>

<p style="text-align:center;"><strong>&nbsp; &nbsp; &nbsp; &nbsp; Attn: Mr.Abhishek Tyagi</strong></p>

<p style="text-align:center;"><strong>Designation:</strong> , </p>

<p style="text-align:center;"><strong>Corporate Address:</strong> </p>

<p>&nbsp;</p> 
         </div>
 


















</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ScriptSecton" runat="server">
</asp:Content>
