<%@ Page Title="" Language="C#" MasterPageFile="~/master-all.Master" AutoEventWireup="true" CodeBehind="Term_Condition.aspx.cs" Inherits="A2ZGymSolution.Term_Condition" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div style="width: 1200px; margin-left:80px; margin-right:50px">
 <div style="margin-left:20px; margin-right:20px">
        <div style="text-align:center;"><h1>Term & Condition</h1></div><br/><br/>

<p style="text-align:center;"> This electronic record is generated by a computer system and does not require any physical or digital signatures. This electronic record is published in accordance with the relevant provisions of the Information Technology Act, 2000 and rules made thereunder.</p>

<p>&nbsp;</p>

<p><strong>1. <u>Introduction</u></strong></p>

<p>&nbsp;</p>

<p><strong>1.1</strong> Please note that<strong> (a)</strong> the domain name www.A2z.com (the “<strong>Website</strong>”); and <strong>(b)</strong> the software application for use on small, wireless computing devices such as smartphones and tablets and also for use on desktop or laptop computers (<strong>(a)</strong> and <strong>(b)</strong> hereinafter collectively referred to the “<strong>Electronic Media</strong>”) is owned, controlled, managed and/or operated by ASR Market Ventures Pvt. Ltd., a private limited company incorporated in accordance with the laws of India, either itself and/or through its parent company, its subsidiaries or its affiliates (hereinafter collectively referred to as the (“<strong>Company</strong>”).</p>

<p>&nbsp;</p>

<p><strong>1.2</strong> The Company provides it online products, software applications, services and content to its Users (as defined below) (“<strong>Service</strong>”) through the Electronic Media subject to the following Terms of Service (“<strong>T&amp;C</strong>”). A2z is one such monthly subscription service, offered by the Company, that can be availed by a person/user/consumer/customer/client, who is registered with the Website or other Electronic Media owned, controlled, managed and/or operated by the Company (“<strong>Members</strong>”), which gives such Member access to various gymnasiums/fitness studios/workouts/health clubs/premises of trainers across the cities which are registered with the Company (“Fitness Service Providers”) in which such customer is geographically located on the (“<strong>T&amp;Cs</strong>”) contained herein.</p>

<p>&nbsp;</p>

<p><strong>1.3</strong> It is clarified by way of Services provided in furtherance of subscription of A2z, the Website, Electronic Media and the Company merely endeavours to provide a web and/or electronic media based platform for increasing your outreach to various cross sections of society, and pursuant to the use of which the Members can interact and exchange information with Fitness Service Providers; avail facilities and service offered by Fitness Service Providers; and subsequently become a Fitness Service Provider’s full time members.</p>

<p style="margin-left:80px;">&nbsp;</p>

<p>&nbsp;</p>

<p><strong>2. <u>Acceptance of the Terms</u></strong></p>

<p>&nbsp;</p>

<p><strong>1</strong>. For the purpose of these T&amp;C, wherever the context so requires, references to “<strong>you</strong>” shall mean the “<strong>User</strong>” (as defined below) including the “<strong>Subscribing Organization</strong>” (as defined below) and references to “<strong>us</strong>” or “<strong>we</strong>” shall mean the “<strong>Company</strong>”.</p>

<p>&nbsp;</p>

<p><strong>2</strong>. Please read the following T&amp;C. Any access to and use of the Electronic Media (including, inter alia, availing the Services) by a you / user of the Electronic Media will be strictly governed by the T&amp;C and is based on the condition that the you / user of the Electronic Media agree to the T&amp;C constitutes, which a legally binding agreement between you and the Company. By using the Electronic Media and/or the Services, you and your Subscribing Organization (as defined below), if any, expressly signify your/their consent to agree and to be bound by the T&amp;C. Without prejudice to the aforesaid, after signing-up/ logging-in as a User on the Website and/or other Electronic Media, you and your Subscribing Organization will be deemed to have accepted these T&amp;C when you click the “<strong>I have read and agreed to the terms and conditions</strong>” at the time of signing-up/logging-in/ registering to become a User on the Website and/or other Electronic Media. You can review the latest version of the T&amp;C at any time on the Electronic Media.</p>

<p>&nbsp;</p>

<p><strong>3</strong>. We reserve the right to revise, update and amend these T&amp;C at any time without prior notice to you and you agree to be bound by the same. It is your responsibility to review these T&amp;C periodically for updates / changes. In the event we revise, update or amend these T&amp;C, we will use our best endeavours to display a notice to this effect on the Electronic Media. The most current form of the T&amp;C can be found at http://www.A2z.co.in/terms-and-conditions Your continued use of the Electronic Media and/or the Services after any revision, updation or amendment of these T&amp;C shall be deemed to be your express acceptance or acceptance by conduct, of any such revised, updated or amended T&amp;C as well.</p>

<p>&nbsp;</p>

<p><strong>4</strong>. In addition, your use and access to the Electronic Media and the services provided by us through the Electronica Media, is subject to the guidelines, rules, privacy policy, specific terms and conditions and/or other applicable policies and procedures (“<strong>Company Policies</strong>”) applicable to such service, which shall be posted on the Electronic Media from time to time. Unless otherwise provided for in any specific Company Policy, the Company Policies shall be deemed to be incorporated into this T&amp;C and shall be considered as part and parcel of hereof. Therefore, by impliedly or expressly agreeing to be bound by the T&amp;C, you also agree to be bound by the Company Policies, as may be updated, amended or revised from time to time.</p>

<p style="margin-left:80px;">&nbsp;</p>

<p>&nbsp;</p>

<p><strong>3. <u>Category of and Transactions Between Users</u></strong></p>

<p>&nbsp;</p>

<p><strong>3.1</strong> The Website, Electronic Media and the Services are designed to provide an online interactive marketplace/electronic platform, inter alia, relating to availing and provision of personal health development training etc., to a wide variety and category of users which broadly includes both the Members who want to avail such services and training and Fitness Service Providers who possess the requisite knowledge, expertise and have the necessary facilities to provide/impart such health development training.</p>

<p>&nbsp;</p>

<p>To clarify, the Company, by way of the web and/or electronic media based platform, merely acts as an intermediary between two broad category of users i.e., <strong>(i)</strong> first category i.e., Members: person/user/consumer/customer/client etc. who want to exchange information, become aware of and learn, develop or acquire professional training; and <strong>(ii)</strong> second category i.e., Fitness Service Providers: gymnasiums/fitness studios/workouts/health clubs/ trainers etc. who have the necessary skillset, qualification, facilities and expertise to impart and offer health development training and services to the Members (the first category of users i.e. the Members and the second category of users i.e., the Fitness Service Providers are collectively referred to as “<strong>Users</strong>”).</p>

<p>&nbsp;</p>

<p><strong>3.2</strong> It is acknowledged and agreed that by way of subscription of the A2z through the Electronic Media, the Members will only have the access and the right to use the facilities, products and services offered by the Fitness Service Providers (who have participated in this programme of the Company) present across various geographical locations in the city (i.e., at present across over 70 locations in New Delhi and National Capital Regions). It is clarified that that Fitness Service Providers will not charge or levy and fee, costs, expenses etc. for the access and use of your facilities (other than the merchandise which may be sold by the Fitness Partner or any third party at the premises of the Fitness Service Provider at maximum retail price).</p>

<p>&nbsp;</p>

<p>Provided, however, that a Member shall have upto five (5) free access and usage to facilities, products and services of the Fitness Service Provider at one (1) particular geographical location in the city during a particular month (“<strong>Specific Location Free Access</strong>”). It is agreed that if during any particular month the Specific Location Free Access have been used and exhausted by a Member, and such Member purports to use furthers facilities, products and services of the same Fitness Service Provider at the same geographical location, then the Fitness Service Provider will be entitled to decline access to or to charge such Member with such fee/charges as are the then applicable to other users/customers/clients/consumers of the Fitness Service Provider.</p>

<p>&nbsp;</p>

<p>In the event, after the expiry of the Specific Location Free Access or any further extended trials/access granted by the Fitness Service Provider pursuant to the A2z scheme, the Member and the Fitness Service Provider may enter into any arrangement/agreement with regard to the use of the facilities, services and access provided by the Fitness Service Provider to a Member, the same will constitute a standalone and independent agreement between the Fitness Service Provider and the Member, and the Fitness Service Providers and the Members will be solely responsible for such agreement. It is clarified that the Company will not be liable for enforcing any such agreement that was made between and Fitness Service Provider and a Member.</p>

<p>&nbsp;</p>

<p><strong>3.3</strong> In view of the aforesaid, it is further clarified that the Company, the Electronic Media and the Services are just designed to act as an intermediary between and with a view to increase the out-reach between the Members and Fitness Service Providers and are not directly involved in/ have no role in any exchange of information, provision/availing of services, any other transaction of whatsoever nature between the Members and Fitness Service Providers. Therefore, the Company will not, in any manner whatsoever, be liable for any and all damages, losses, penalties, liabilities, obligations, fines, costs, expenses, interests or claims (whether direct or indirect, known or unknown, foreseen or unforeseen) (“<strong>Losses</strong>”) incurred by any Users due to or arising out of or in connection with any transaction between the aforesaid categories of Users; or out of the use/availing/provision of the facilities/services/premises by a User to other Users; breach of these T&amp;C and the Company Policies (as defined below) by a User.</p>

<p>&nbsp;</p>

<p><strong>3.4</strong> Each User is solely responsible for every transaction occurring under his or her account. The Company does not verify the skills, qualifications, credentials, background etc. of any of the Fitness Service Providers and the quality of services offered by them. It is strongly recommended that every Member should independently verify the skills, qualifications, credentials, background etc. of each Fitness Service Provider from whom such Member receives or contemplates to receive advice or services.</p>

<p>&nbsp;</p>

<p><strong>3.5</strong> You acknowledge and agree that Fitness Service Providers are not the employees, agents, representatives, contractors, partners of the Company and the Company takes no responsibility for any act, omission, advice, service, representation, etc. of any such Fitness Service Provider. As further described in this T&amp;C, the Company makes no representation, warranty or guarantee whatsoever as to <strong>(a)</strong> the availability of/access provided by the Fitness Service Providers; <strong>(b)</strong> the accuracy of the representations made or the information posted on the Electronic Media by the Fitness Service Provider; <strong>(c)</strong> the accuracy of the information exchanged between the Fitness Service Provider and the Member; <strong>(d)</strong> the quality, nature, usefulness, relevance, accuracy of the services provided by the Fitness Service Providers etc.&nbsp;</p>

<p>&nbsp;</p>

<p>&nbsp;</p>

<p><strong>4. <u>User Account, Password And Security</u></strong></p>

<p>&nbsp;</p>

<p><strong>4.1</strong> Use of the Electronic Media and the availing of the Services are available only to all natural and legal persons who have the capacity to enter into legally binding contracts as per the Indian Contract Act, 1872. You hereby represent and warrant to the Company that you are at least eighteen (18) years of age or above or have the authority to enter into these T&amp;C. Further, you represent that you are capable of entering, performing and adhering to these T&amp;C and that you agree to be bound by the following terms and conditions. Further, if you are using or opening an account on the Website or the Electronic Media on behalf of a company, entity, or organization (a “<strong>Subscribing Organization</strong>”) then you represent and warrant that you are an authorized representative of that Subscribing Organization with the authority to bind such organization to these T&amp;Cs; and agree to be bound by these T&amp;Cs on behalf of such Subscribing Organization.</p>

<p>&nbsp;</p>

<p>While individuals under the age of 18 may use the Website/Electronic Media or utilize the Services, they shall do so only with the involvement &amp; guidance of their parents and / or legal guardians, under such parent /legal guardian’s supervision and control. We reserve the right to deny use/membership to, and/or exclude from our Electronic Media, any person in our absolute discretion and we al also reserve the right to suspend, revoke or amend your use/membership in our absolute discretion.</p>

<p>&nbsp;</p>

<p><strong>4.2</strong> You can become a Member/Fitness Service Provider and have your own account with the Company by signing-up and registering with us.</p>

<p><strong>4.2.1</strong> Member Sign-in and Registration</p>

<p>&nbsp;</p>

<p><strong>4.2.1.1</strong> To Members, the Company offers sign-up/logging-in process with our own sign-up system and through other platforms such as Facebook and Google. A Member can complete our own sign-up process by<strong> (i)</strong> providing us with current, complete and accurate information as prompted by the applicable sign-up form; or <strong>(ii)</strong> a Member can directly sign-in using the Facebook and Google connect platforms by way of which we will collect the requisite information through the information provided/feeded by a Member on Facebook and Google.</p>

<p>&nbsp;</p>

<p>It is clarified that Facebook and Google connect as a medium for signing up only. A Member hereby agrees that the his/her data collected by the Company through the above mediums which will be provided by a Member i.e., the intended user through your Facebook or Google profile, can be used, preserved, processed and disclosed by the Company in accordance with the T&amp;C herein, Privacy Policy and other Company Policies. However, kindly note that the manner in which Facebook and Google uses, stores, processes and discloses a Member’s information is governed solely by their policies, and the Company and the Electronic Media bears no liabilities/responsibility for their privacy practices; the manner in which Facebook and Google uses, stores, processes and discloses your information; and/or other actions of any third party site or service that may be enabled within the services provided by Facebook and Google.&nbsp;</p>

<p>&nbsp;</p>

<p><strong>4.2.1.2</strong> Post the sign-up process (either by way of a Member’s own sign up process or through Facebook and Google), a Member will be required to carry out and undertake a registration process. At the time of registration, a Member will be required to given certain information and also click the “<strong>I have read and agreed to the terms and conditions</strong>” tab. By clicking on the “<strong>I have read and agreed to the terms and conditions</strong>” tab, a Member will be deemed to have agreed to provide the information requested by us and also be deemed to have accepted the T&amp;C.</p>

<p>&nbsp;</p>

<p><strong>4.2.2</strong> Fitness Service Provider’s Sign-in and Registration</p>

<p>&nbsp;</p>

<p><strong>4.2.2.1</strong> For becoming a Fitness Service Provider, To sign up for the Services and become a User, a Fitness Service Provider has to open the unique URL provided to such Fitness Service Provider by the Company and thereby complete the signing up process by providing us with current, complete and accurate information as prompted by the applicable sign-up form. Upon completion of the sign-up/registration form, the Fitness Service Provider will receive an automated e-mail with its user name and initial password, using which the Fitness Service Provider will be required to given certain information and also click the “<strong>I have read and agreed to the terms and conditions</strong>” tab, so as to gain access to the account on the Electronic Media/Website/A2z page. The Fitness Service Provider is mandatorily required to replace the automated password and create a new password for its profile/page on the Electronic Media/Website/A2z. By clicking on the “<strong>I have read and agreed to the terms and conditions</strong>” tab, the Fitness Service Provider will be deemed to have agreed to provide the information requested by us and also be deemed to have accepted the T&amp;C.</p>

<p>&nbsp;</p>

<p><strong>4.3</strong> A User should provide accurate information at the time of sign-up and registration process and update such information from time to time in case of any change thereto. You are solely responsible for maintaining the confidentiality of your account, display name and password and you are fully responsible for all activities that occur under the same. It is clarified and agreed between the parties that you are solely responsible for maintaining the confidentiality of your account and password and for restricting access to your computer, and you agree to accept responsibility for all activities that occur under your account, display name and password and the Company shall not be liable or responsible whatsoever in this regard. You agree to register prior to uploading any content and / or comment and any other use or services of the Electronic Media and provide your details including but not limited to complete name, age, email address, residential address, contact number, location etc. By signing up, you agree to the T&amp;C in addition to any other specific terms which shall be posted at an appropriate location of the Electronic Media.</p>

<p>&nbsp;</p>

<p><strong>4.4</strong> The Services are designed to increase and facilitate interaction and transaction between Member and Fitness Service Providers. For the aforesaid purpose it essential that you display, keep and maintain accurate and detailed information about you, including but not limited to your expertise, services, areas of interest, workouts, schemes, offers, details of facilities/premises, workout schedules, charges, schedule of open and empty slots, trainers available, etc., in your account and under your display name on the Electronic Media. Without prejudice to the generality of the above, the Fitness Service Providers agrees to provide to the Members at least all the facilities, services offers and schemes as are displayed under your account and display name, on the Electronic Media and hence the Fitness Service Providers are more so required to ensure that this information is kept accurate and up-to-date at all times</p>

<p>&nbsp;</p>

<p><strong>4.5</strong> You expressly agree to <strong>(a)</strong> immediately notify the Company of any actual or potential unauthorized use of your account, display name and password or account or any breach of security or any breach of these T&amp;C by a third party; and <strong>(b)</strong> log-out from your account at the end of each session in order to ensure complete security and secrecy of your data and the Company’s data. Upon receiving a notification of any actual or potential unauthorised use, the Company will take action to block access to such account and your account, display name and password at the earliest and take all other actions as required under law. You agree that the Company cannot and will not be liable for any loss or damage arising from your failure to comply with the T&amp;C.</p>

<p>&nbsp;</p>

<p><strong>4.6</strong> You agree that you will act lawfully, diligently and honestly at all times when you access and use the Electronic Media and/or avail the Services and will comply with all laws, rules, regulations, legislations, notifications, circulars, guidelines, standards, codes, policies, orders, approvals, ordinances, judgments, decrees, injunctions, writs, arbitral award, bye-laws, or any similar form of decision, determination, or adjudication having the force of law, as amended from time to time, applicable to your use of the Electronic Media and/or availing the Services.</p>

<p>&nbsp;</p>

<p><strong>4.7</strong> You agree that you will not interfere with, jeopardise, disrupt or harm the Electronic Media and/or Services and that you will not intercept, expropriate, re-use, steal or re-utilise any system, data, photographs or information comprised in or provided to you via the Electronic Media and/or Services and at all times comply with these T&amp;C and the Company Policies.</p>

<p>&nbsp;</p>

<p><strong>4.8</strong> We will provide you with any help you may reasonably require to access the Electronic Media but we shall not be responsible if you are unable to access any of the Electronic Media or any of the Services for any reason. We do not guarantee you access to the Electronic Media at any time and all times. We do not guarantee that while you are accessing the Electronic Media, your access will be uninterrupted, without delay/interference, secure and/or error free or operate as set out and anticipated in these T&amp;C. Accordingly, we reserve the right, at any time, to suspend or discontinue the Electronic Media and/or any of the Services for any reason without incurring any liability or obligation to you.</p>

<p>&nbsp;</p>

<p><strong>4.9</strong> You agree that the information you provide to the Company on the Electronic Media at the time of registration and any time thereafter and any information displayed under your account at all times will be true, accurate, current, and complete. If you provide any information that is untrue, inaccurate, not current or incomplete or we have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this T&amp;C and the Company Policies, we shall have the right to indefinitely suspend or terminate or block access of your membership on the Electronic Media and refuse to provide you with access to the Electronic Media.</p>

<p>&nbsp;</p>

<p><strong>4.10</strong> Please note that any person accessing the Electronic Media and registering on the Electronic Media on behalf of Subscribing Entity shall be deemed to have been duly authorized by the Subscribing Entity for this purpose and also to carry out the activities on the Electronic Media. The Company will not be liable for any activities executed on behalf of any Subscribing Entity by a person not authorized by such Subscribing Entity.</p>

<p>&nbsp;</p>

<p><strong>4.11</strong> If the Company reasonably believes that an account and password is being used / misused in any manner, the Company shall reserve the right to cancel access rights immediately without notice, and block access to all users from that IP address. You agree to notify the Company and the Electronic Media immediately of any unauthorized use of your account or any other breach of security. The Company will not be liable for any loss that you may incur as a result of someone else using your password or account. However, you could be held liable for Losses incurred by the Company, Website, A2z or another party due to someone else using your account or password.</p>

<p>&nbsp;</p>

<p><strong>4.12</strong> Further, by using the Electronic Media or sending emails, data, information or communication to the Company through the Electronic Media you consent to receive communications via electronic records from the Company periodically and as and when required.</p>

<p style="margin-left:80px;">&nbsp;</p>

<p>&nbsp;</p>

<p><strong>5. <u>Privacy</u></strong></p>

<p>&nbsp;</p>

<p><strong>5.1</strong> When you become a User, then and during your use of the Electronic Media and/or Services, you will provide us with certain information and other data as aforesaid that may or may not be otherwise publicly available. We will respect the privacy of such data as per our Privacy Policy which is available at http://www.A2z.co.in/privacy-policy/. We will only collect, use, disclose or process your data in accordance with our Privacy Policy, which you accept by your continued use of the Electronic Media and/or the Services. We will share your data with other parties only as set out in our Privacy Policy.</p>

<p>&nbsp;</p>

<p>In addition to and not in contravention of the terms, measures and procedures regarding storing and securing the data and information on the Electronic Media as stipulated in the Privacy Policy, you acknowledge, accept and agree that the Company utilizes Yii standard security configurations for securing data and information on the Electronic Media which is reasonable and sufficient security practice and procedure as per the industry standard and for the purposes of Information Technology Act, 2000 and the rules and regulations made thereunder.</p>

<p>&nbsp;</p>

<p><strong>5.2</strong> The User agree that in case of any leakage, destruction, unauthorized access or the like to information stored on the Company’s Electronic Media, they waive their right to file a complaint for compensation under all applicable laws.</p>

<p style="margin-left:80px;">&nbsp;</p>

<p>&nbsp;</p>

<p><strong>6. <u>Terms of Use</u></strong></p>

<p>&nbsp;</p>

<p><strong>6.1</strong> In addition to other restrictions that may be set forth in the T&amp;C, the User agrees not to:</p>

<p>&nbsp;</p>

<p><strong>1</strong>. host, display, upload, modify, publish, transmit, update or share any information that:</p>

<p><strong>a)</strong> belongs to another person and in relation to which it does not have any right of use;</p>

<p><strong>b)</strong> infringes intellectual property rights (including any patent, trademark, copyright or other proprietary rights) of any person and privacy rights of any person;</p>

<p><strong>c)</strong> is false or misleading in any way;</p>

<p><strong>d)</strong> violates any law for time being in force;</p>

<p><strong>e)</strong> harasses or advocates harassment of another person;</p>

<p><strong>f)</strong> involves the transmission of “<strong>junk mail</strong>”, “<strong>chain mail</strong>” or unsolicited mass mailing or “<strong>spamming</strong>”;</p>

<p><strong>g)</strong> promotes illegal activities or abusive, obscene, defamatory or libellous conduct;</p>

<p><strong>h)</strong> solicits gambling or engages in any gambling activity which is or could be construed as being illegal;</p>

<p><strong>i)</strong> harms minors in any way;</p>

<p><strong>j)</strong> is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another’s privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to “<strong>indecent representation of women</strong>” within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;</p>

<p><strong>k)</strong> deceives or misleads the other Users about the origin of messages or communicates any information which is grossly offensive or menacing in nature;</p>

<p><strong>l)</strong> threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation;</p>

<p><strong>m)</strong> promotes an illegal or unauthorized copy of another person's copyrighted work;</p>

<p><strong>n)</strong> provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;</p>

<p><strong>o)</strong> provides instructional information about illegal activities such as making or buying illegal weapons, violating someone’s privacy, or providing or creating computer viruses;</p>

<p><strong>p)</strong> tries to gain unauthorized access or exceeds the scope of authorized access to the Electronic Media or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Electronic Media or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;</p>

<p><strong>q)</strong> refers to any website or URL that, in our sole discretion, contains material that is inappropriate for the Electronic Media or any other website, application, software contains content that would be prohibited or violates the letter or spirit of these T&amp;C;</p>

<p>&nbsp;</p>

<p><strong>2</strong>. use or access any service, information, application or software available via the Electronic Media in a manner not expressly permitted by the Company;</p>

<p><strong>3</strong>. reveal/disclose confidential or proprietary information of other Users, the Company or any third party, in any manner whatsoever;</p>

<p><strong>4</strong>. incorporate any computer contaminant, software virus or any computer code or file or program on the Electronic Media designed to interrupt, destroy or limit the functionality of the Electronic Media;</p>

<p><strong>5</strong>. incorporate or introduce any program on the Electronic Media that might infringe the intellectual property rights of any other User or of the Company;</p>

<p><strong>6</strong>. download, copy, reproduce any file or information available on the Electronic Media that the User knows, or reasonably should know, cannot be legally reproduced, displayed, performed, and/or distributed;</p>

<p><strong>7</strong>. in any way deface or vandalize this Electronic Media or prevent or restrict others from using this Electronic Media;</p>

<p><strong>8</strong>. &nbsp;stalks, threaten or harass any other User or infringe upon or attempt to infringe upon their privacy.</p>

<p><strong>9</strong>. infringe any patent, trademark, copyright or other proprietary rights or third party’s trade secrets or rights of publicity or privacy, of the Company, other Users or any third Party;</p>

<p><strong>10</strong>. impersonate any person or entity, or falsely state or otherwise misrepresent themselves or their affiliation with any person or entity;</p>

<p><strong>11</strong>. directly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force;</p>

<p><strong>12</strong>. create liability for the Company or cause the Company to lose (in whole or in part) the services of its internet service provider or other suppliers.</p>

<p>&nbsp;</p>

<p><strong>6.2</strong> You shall not use any “<strong>deep-link</strong>”, “<strong>page-scrape</strong>”, “<strong>robot</strong>”, “<strong>spider</strong>” or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Electronic Media or any product/service, or in any way reproduce or circumvent the navigational structure or presentation of the Electronic Media or any product/service, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Electronic Media. We reserve the right to bar any such activity.</p>

<p>&nbsp;</p>

<p><strong>6.3</strong> You shall not attempt to gain unauthorized access to any portion or feature of the Electronic Media or any product/service, or any other systems or networks connected to the Electronic Media or to any server, computer, network, or to any of the product/services offered on or through the Electronic Media, by hacking, password “<strong>mining</strong>” or any other illegitimate means.</p>

<p>&nbsp;</p>

<p><strong>6.4</strong> You shall not probe, scan or test the vulnerability of the Electronic Media or any network connected to the Electronic Media nor breach the security or authentication measures on the Electronic Media or any network connected to the Electronic Media. You may not reverse look-up, trace or seek to trace any information on any other User of or visitor to Electronic Media, or any other client/customer/user/member of the Company/ Website/ A2z, including any account on the Electronic Media not owned/operated/managed by you, to its source, or exploit the Electronic Media or any product/service or information made available or offered by or through the Electronic Media, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than your own information, as provided for by the Electronic Media.</p>

<p>&nbsp;</p>

<p><strong>6.5</strong> You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about the Company/Website/Company’s products and services or the brand name or domain name used by the Company including the terms such as “Skillhippo”, “A2z” etc., or otherwise engage in any conduct or action that might tarnish the image or reputation of the Company/Website/A2z or other Users on the Electronic Media or other business partners of the Company or otherwise tarnish or dilute any of the Company’s trade or service marks, trade name and/or goodwill associated with such trade or service marks, trade name as may be owned or used by the Company.</p>

<p>&nbsp;</p>

<p><strong>6.6</strong> You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal you send to us on or through the Electronic Media or any product/service offered on or through the Electronic Media.</p>

<p>&nbsp;</p>

<p><strong>6.7</strong> You may not use the Electronic Media or any content thereof for any purpose that is unlawful or prohibited by these T&amp;C, or to solicit the performance of any illegal activity or other activity which infringes the rights of the Company, its Users and/or others third parties.</p>

<p>&nbsp;</p>

<p><strong>6.8</strong> You shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000 and rules thereunder as applicable and as amended from time to time and also all applicable laws, rules and regulations and international laws, statutes, ordinances and regulations regarding use of the Services and the transactions between you and other Users.</p>

<p>&nbsp;</p>

<p><strong>6.9</strong> No User shall solicit (directly or indirectly) any other Users of the Electronic Media to avail or provide any products/services being displayed on the Electronic Media, either independently or through a third party except through the Company/Electronic Media/A2z.</p>

<p>&nbsp;</p>

<p><strong>6.10</strong> The User shall indemnify and hold harmless the Company, its owners, licensees, affiliates, subsidiaries, group companies (as applicable) and their respective officers, directors, agents, and employees, from all Losses, claims, damages, penalties, costs, expenses, demands, actions (including reasonable attorneys’ fees) suffered or incurred by the Company due to or arising out of breach of this T&amp;C and other Company b Policies.&nbsp;</p>

<p>&nbsp;</p>

<p><strong>6.11</strong> To enable use of your information supplied by you to us, so that use of any such information by us is not construed as a violation of any rights, you agree to grant us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights you have in your information, in any media now known or not currently known, with respect to your information. We will only use your information in accordance with the T&amp;C and the Company Policies applicable to use of the Electronic Media.</p>

<p>&nbsp;</p>

<p><strong>6.12</strong> We reserve the right, but have no obligation, to monitor the materials posted on the Electronic Media and shall have the right to remove or edit any content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these T&amp;C. Notwithstanding this right, you shall remain solely responsible for the content of the materials you post on the Electronic Media and in your private messages.</p>

<p>&nbsp;</p>

<p><strong>6.13</strong> It is possible for other Users to obtain your information due to your use of the Electronic Media and such recipient may harass or injure you. We do not approve of such unauthorized uses, but by using the Electronic Media you acknowledge and agree that we are not responsible for the use of any information that you publicly disclose or share with others on the Electronic Media. Please carefully select the type of information that you publicly disclose or share with others on the Electronic Media.</p>

<p style="margin-left:80px;">&nbsp;</p>

<p>&nbsp;</p>

<p><strong>7. <u>Objectionable Conduct</u></strong></p>

<p>&nbsp;</p>

<p><strong>7.1</strong> Under no circumstances shall the Company be held responsible or liable, in any way, for any conduct of a User in their interactions with/use of premises/facilities of other Users or uploading of any content by a User on the Electronic Media or any other electric or print media/platform, including any publishing of any content which, in legal opinion, is derogatory, threatening, defamatory, obscene or offensive or offends public sensibilities or morals.</p>

<p>&nbsp;</p>

<p><strong>7.2</strong> However, if a User stalks, sexually harasses, causes metal harassment to, abuses and/or uses derogatory language and indulgences in physical violence, the Company shall (i) suspends the account of such User and discontinue provision of the services to such User and; and/or (i) the relevant User shall not allow access to their facilities or premises to such User.</p>

<p style="margin-left:80px;">&nbsp;</p>

<p>&nbsp;</p>

<p><strong>8. <u>Specific obligations of Fitness Service Providers and Members</u></strong></p>

<p>&nbsp;</p>

<p><strong>8.1</strong> The Members agree to:</p>

<p><strong>1</strong>. make timely payment of the fees/charges etc. as agreed and due to the Company; and</p>

<p><strong>2</strong>. comply with the community guidelines/rules/regulations any other guidelines prescribed by the Fitness Service Provider at the time of utilising the services thereof and the use/access to the premises/facilities of the Fitness Service Provider.</p>

<p>&nbsp;</p>

<p><strong>8.2</strong> The Fitness Service Provider agrees to:</p>

<p><strong>a)</strong> provide services, products, training etc. to the Members in conformity with the data, information, offers, schemes, advertisement provided, posted by them on the Electronic Media or communicated to the Users;</p>

<p><strong>b)</strong> not discriminate between any Members, including but not limited to, on the basis of caste, creed, sex and religion;</p>

<p><strong>c)</strong> not to accept any walk-ins for a programme solely marketed on the Electronic Media as being fully registered/subscribed;</p>

<p><strong>d)</strong> inform the Member about that they should transact through the Electronic Media, unless otherwise agreed between the Fitness Service Provider and the Company; and</p>

<p><strong>e)</strong> comply with the community guidelines/rules/regulations any other guidelines prescribed by the Member at the time of providing the services at the premises/facilities of the Member.</p>

<p style="margin-left:120px;">&nbsp;</p>

<p>&nbsp;</p>

<p><strong>9. <u>Payment/Commercial Terms and Refund</u></strong></p>

<p>&nbsp;</p>

<p><strong>9.1</strong> Payments by Users to the Company shall be made in full by using the available payment option. Payment terms are governed by the terms and conditions of service of the third party payment service provider. The Company shall not be liable for any action or omissions or deficiency in service for any third party payment service provider. Upon confirmation of receipt of payment by the third party payment solution provider, the A2z will be issued which needs to be produced at the premises of the Fitness Service Provider.</p>

<p>&nbsp;</p>

<p><strong>9.2</strong> In case the Member is not able to make it to programme, workout, facility after signing up and having paid for the same, no pay-back will be offered and it will be treated as a ‘no-show’. After booking on a programme, workout, facility etc., the Member shall not be able to cancel a programme, workout, facility etc. Not turning up for programme, workout, facility will render a ‘no-show’.</p>

<p style="margin-left:80px;">&nbsp;</p>

<p>&nbsp;</p>

<p><br><strong>10. <u>Disclaimers, Waivers and Release</u></strong></p>

<p>&nbsp;</p>

<p>THE USER EXPRESSLY UNDERSTANDS AND AGREES THAT:</p>

<p>&nbsp;</p>

<p><strong>10.1</strong> THE ACCESS TO FACILITIES, WORKOUTS, ACTIVITIES, AND ANY OTHER SERVICES OFFERED TO OR THAT CAN BE AVAILED BY A MEMBER BY WAY OF SUBSCRIPTION OF A2z, ARE OFFERED AND PROVIDED BY YOU AT YOUR SOLE RISK, AND HENCE YOU AGREE THAT THE COMPANY SHALL BE IN NO EVENT LIABLE FOR ANY INJURY, LOSSES, CLAIM, DAMAGE OR ANY SPECIAL, EXEMPLARY, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL DAMAGES OF ANY KIND, WHETHER BASED IN CONTRACT, TORT OR OTHERWISE, WHICH ARISES OUT OF OR IS ANY WAY CONNECTED WITH A MEMBER’S ACCESS TO FACILITIES AND ATTENDANCE AND PARTICIPATION IN THE WORKOUTS, ACTIVITIES, AND ANY OTHER SERVICES OFFERED THE FITNESS SERVICE PROVIDER PURSUANT TO SUBSCRIPTION OF A2z BY A MEMBER</p>

<p>&nbsp;</p>

<p><strong>10.2</strong> IT IS EXPRESSLY UNDERSTOOD, ACKNOWLEDGED AND AGREED THAT THE COMPANY/ WEBSITE/ A2z MERELY BRINGS BOTH THE MEMBER AND THE FITNESS SERVICE PROVIDER ON A COMMON PLATFORM IN ORDER TO INCREASE THE ACCESSIBILITY OF THE VARIOUS FITNESS SERVICE PROVIDERS TO THE MEMBERS AND HAS NO ROLE IN ACTUAL USE OF THE FACILITIES, SERVICES AND ACCESS PROVIDED BY THE FITNESS SERVICE PROVIDER TO THE MEMBER. THUS, THE COMPANY, ITS AFFILIATES, OR ANY OF THE FOREGOING'S OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, SUB-CONTRACTORS, REPRESENTATIVES, AGENTS ETC. DISCLAIMS ALL LIABILITY, WARRANTIES AND RESPONSIBILITIES IN RESPECT OF THE USE OF THE FACILITIES/SERVICES BY THE MEMBER AND ACCESS PROVIDED BY THE FITNESS SERVICE PROVIDER. FURTHER, THE USER AGREES TO INDEMNIFY THE COMPANY, ITS AFFILIATES, AND/ OR ANY OF THE FOREGOING'S OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, SUB-CONTRACTORS, REPRESENTATIVES, AGENTS ETC. FOR ANY AND ALL LOSSES ARISING IN CONNECTION WITH THE USE OF THE FACILITIES/ SERVICES BY THE MEMBER AND ACCESS PROVIDED BY THE FITNESS SERVICE PROVIDER.</p>

<p>&nbsp;</p>

<p><strong>10.3</strong> THE USER SHALL NOT HAVE ANY PLEA, CLAIM OR DEMAND AGAINST THE COMPANY, ITS AFFILIATES, AND THEIR RESPECTIVE OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, SUB-CONTRACTORS AND AGENTS ETC. IN RESPECT OF ANY ACCESS OR SERVICES THE FITNESS SERVICE PROVIDER PROVIDES TO THE MEMBERS IN CONNECTION WITH THE USE OF A2z. THE COMPANY, WEBSITE AND A2z WILL NOT BE DEEMED THE PROVIDER OR RECIPIENT OF ANY SERVICES ACQUIRED THROUGH THE SUBSCRIPTION OF A2z BY A MEMBER OR PURSUANT TO REGISTRATION OF A PERSON AS A FITNESS SERVICE PROVIDER WITH THE COMPANY, WEBSITE AND/OR A2z.</p>

<p>&nbsp;</p>

<p><strong>10.4</strong> USE OF THE SERVICE AND THE ELECTRONIC MEDIA IS AT THE SOLE RISK OF THE USER. THE SERVICE, PRODUCTS, SOFTWARE APPLICATIONS AND ANY OTHER CONTENT IS PROVIDED ON AN “<strong>AS IS</strong>” AND “<strong>AS AVAILABLE</strong>” BASIS, AND THEREFORE A USER WILL NOT HAVE ANY CLAIM OR DEMAND AGAINST THE COMPANY, ITS AFFILIATES, OR ANY OF THE FOREGOING'S OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, SUB-CONTRACTORS, REPRESENTATIVES, AGENTS ETC. WITH RESPECT TO THE SERVICES, ELECTRONIC MEDIA OR FITNESS SERVICE PROVIDER. SO FAR AS PERMITTED BY LAW, THE COMPANY EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF SATISFACTORY QUALITY, MERCHANTABILITY OR FITNESS FOR OR ANY PARTICULAR PURPOSE AND NON-INFRINGEMENT.</p>

<p>&nbsp;</p>

<p><strong>10.5</strong> THE COMPANY MAKES NO WARRANTY THAT <strong>(I)</strong> THE SERVICE WILL MEET THE REQUIREMENTS OF THE USER; <strong>(II)</strong> THE SERVICE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE; <strong>(III)</strong> THE RESULTS OBTAINED FROM THE USE OF THE SERVICE WILL BE ACCURATE, RELIABLE, COMPLETE OR CURRENT; <strong>(IV)</strong> THE QUALITY OF ANY PRODUCTS, SERVICES, APPLICATION, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY THE USER THROUGH THE SERVICE/ELECTRONIC MEDIA WILL MEET THE EXPECTATIONS OF THE USER; AND <strong>(V)</strong> ANY ERRORS IN THE SERVICE WILL BE CORRECTED. ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE/ELECTRONIC MEDIA IS DONE AT SOLE RISK OF THE USER AND THAT THE USER WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO ITS COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.</p>

<p>&nbsp;</p>

<p><strong>10.6</strong> NO ADVICE, SERVICE OR INFORMATION, OBTAINED BY YOU FROM THE COMPANY/ELECTRONIC MEDIA OR OTHER USERS, OR THROUGH OR FROM THE COMPANY’S SERVICES, SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE T&amp;C.</p>

<p>&nbsp;</p>

<p><strong>10.7</strong> THE COMPANY IS NOT RESPONSIBLE FOR INCORRECT OR INACCURATE INFORMATION, HUMAN ERROR, TECHNICAL MALFUNCTIONS, LOST/DELAYED DATA TRANSMISSION, OMISSION, INTERRUPTION, DELETION, DEFECT, FAILURES OF ANY TELEPHONE NETWORK, COMPUTER EQUIPMENT, SOFTWARE OF ANY COMBINATION THEREOF, OR INABILITY TO ACCESS THE ELECTRONIC MEDIA.</p>

<p>&nbsp;</p>

<p><strong>10.8</strong> FURTHER THE COMPANY DOES NOT GUARANTEE DUE PERFORMANCE OF SERVICES OR ANY OTHER OBLIGATION BY THE FITNESS SERVICE PROVIDER AND THE MEMBER AND SHALL NOT BE RESPONSIBLE FOR ANY BREACH/NON-PERFORMANCE THEREOF. THE COMPANY SHALL NOT BE RESPONSIBLE FOR ANY DISPUTE RESOLUTION OR MEDIATION BETWEEN THE USERS, UNLESS SPECIFICALLY PROVIDED FOR BY THE COMPANY OR IN THE COMPANY POLICIES.</p>

<p>&nbsp;</p>

<p><strong>10.9</strong> THE COMPANY SHALL NOT BE RESPONSIBLE FOR ANY PAYMENTS MADE / TO BE MADE BY THE MEMBER TO THE FITNESS SERVICE PROVIDER. ALL PAYMENTS MADE ON OR THROUGH THE ELECTRONIC MEDIA SHALL BE IN ACCORDANCE WITH THE LAWS OF REPUBLIC OF INDIA AND THE PARTIES MAY BE REQUIRED TO SUBMIT IDENTITY PROOF AND OTHER SUPPORTING DOCUMENTS. BY CONCLUDING TRANSACTIONS ON THE ELECTRONIC MEDIA, THE USERS ARE AUTHORIZING THE COMPANY TO COLLECT, PROCESS AND REMIT THE PAYMENTS.</p>

<p>&nbsp;</p>

<p><strong>10.10</strong> ALL INFORMATION AND CONTENT PROVIDED ON THE ELECTRONIC MEDIA IS INTENDED TO BE GENERAL IN NATURE AND THE USER SHOULD NOT RELY SOLELY ON IT IN CONNECTION WITH MAKING ANY DECISION. THE COMPANY TRIES TO ENSURE THAT ALL INFORMATION PROVIDED ON THE ELECTRONIC MEDIA IS CORRECT AT THE TIME OF INCLUSION ON THE ELECTRONIC MEDIA BUT DOES NOT GUARANTEE THE ACCURACY OF SUCH INFORMATION. THE COMPANY IS NOT LIABLE FOR ANY ACTION TAKEN AS A RESULT OF RELIANCE ON SUCH INFORMATION OR ADVICE OR FOR ANY LOSS OR DAMAGE SUFFERED AS A RESULT OF ANY ACTION TAKEN.</p>

<p>&nbsp;</p>

<p><strong>10.11</strong> THE COMPANY DOES NOT GUARANTEE THAT THE ELECTRONIC MEDIA IS FREE FROM VIRUSES AND THE USER SHALL, FOR ITS OWN PROTECTION, TAKE NECESSARY STEPS TO ENSURE APPROPRIATE SECURITY MEASURES AND MAY UTILIZE A VIRUS SCANNER BEFORE DOWNLOADING ANY INFORMATION, SOFTWARE OR DOCUMENTATION.</p>

<p>&nbsp;</p>

<p><strong>10.12</strong> ANY LINKS TO OTHER WEBSITES/PORTALS ON THE ELECTRONIC MEDIA ARE ONLY FOR CONVENIENCE AND THE COMPANY SHALL NOT RESPONSIBLE FOR THE CONTENTS AND RELIABILITY OF SUCH LINKED WEBSITES/APPLICATIONS AND PORTALS. FURTHER, PRESENCE OF ANY LINKS OR PORTALS ON THE ELECTRONIC MEDIA SHOULD NOT BE ASSUMED AS ENDORSEMENT OF ANY KIND BY THE COMPANY.</p>

<p>&nbsp;</p>

<p><strong>10.13</strong> THE COMPANY DOES NOT REVIEW, ENDORSE, RECOMMEND, VERIFY, EVALUATE, WARRANT OR GUARANTEE THE EXPERTISE, CLAIMS, CREDENTIALS, BACKGROUND ETC. OF ANY FITNESS SERVICE PROVIDER, OR ANYSERVICE, ADVICE, TRAINING, INFORMATION, REPRESENTATION OR OTHER SERVICE PROVIDED BY ANY FITNESS SERVICE PROVIDER. NOTHING CONTAINED IN THIS T&amp;C, ELECTRONIC MEDIA ,, OR ON ANY THIRD PARTY SITE OR PROVIDED OTHERWISE SHALL BE CONSIDERED AS A REFERRAL, ENDORSEMENT, RECOMMENDATION, VERIFICATION, WARRANTY OR GUARANTEE WITH RESPECT TO <strong>(A)</strong> ANY FITNESS SERVICE PROVIDER; OR <strong>(B) </strong>ANY OPINION, SERVICE, ADVICE, TRAINING, INFORMATION OR OTHER SERVICE PROVIDED BY ANY FITNESS SERVICE PROVIDER OR OTHERWISE MADE AVAILABLE ON THE ELECTRONIC MEDIA; OR <strong>(C)</strong> THE VALIDITY, ACCURACY, COMPLETENESS, SAFETY, LEGALITY, QUALITY OR APPLICABILITY OF ANY CONTENT OR ANYTHING OTHERWISE SAID, WRITTEN OR PROVIDED BY ANY FITNESS SERVICE PROVIDER OR CONTAINED IN OR MADE AVAILABLE ON THE ELECTRONIC MEDIA OR ANY OTHER FORUM.</p>

<p>&nbsp;</p>

<p><strong>10.14</strong> THE COMPANY EXPRESSLY DISCLAIMS ALL REPRESENTATIONS AND WARRANTIES RELATED TO INFORMATION POSTED, PROVIDED OR TRANSMITTED BY FITNESS SERVICE PROVIDERS. IF A USER DECIDES TO RELY ON THE INFORMATION POSTED, PROVIDED OR TRANSMITTED BY A FITNESS SERVICE PROVIDER, THE MEMBER MUST EXERCISE A HIGH LEVEL OF CARE, CAUTION AND SCRUTINY. THE MEMBER SHALL NOT HAVE ANY CLAIM OR DEMAND AGAINST THE COMPANY, ITS AFFILIATES, AND/OR ANY OF THE FOREGOING'S OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, SUB-CONTRACTORS AND/OR AGENTS WITH RESPECT TO ANY SERVICE, ADVICE, TRAINING ETC. WHICH THE MEMBER RECEIVES, USES AND/OR RELIES ON. THE COMPANY WILL NOT BE DEEMED THE PROVIDER OF ANY FITNESS SERVICE PROVIDER’S SERVICES OR OTHER INFORMATION ACQUIRED THROUGH THE ELECTRONIC MEDIA. THE PURCHASE OF THE SERVICES OFFERED BY ANY FITNESS SERVICE PROVIDER IS ENTIRELY AT THE USER'S SOLE RISK.&nbsp;</p>

<p>&nbsp;</p>

<p><strong>10.15</strong> IT IS EXPRESSLY UNDERSTOOD, ACKNOWLEDGED AND AGREED BY THE USER THAT THE COMPANY/ WEBSITE/ELECTRONIC MEDIA MERELY BRINGS THE USERS I.E., THE FITNESS SERVICE PROVIDER AND MEMBER ON A COMMON PLATFORM IN ORDER TO FACILITATE INTERACTION AND TRANSACTION BETWEEN MEMBER AND FITNESS SERVICE PROVIDERS AND THE COMPANY HAS NO ROLE NO ROLE IN ANY EXCHANGE OF INFORMATION, PROVISION/AVAILING OF SERVICES AND QUALITY THEREOF, OR ANY OTHER TRANSACTION OF WHATSOEVER NATURE BETWEEN THE MEMBERS AND FITNESS SERVICE PROVIDERS AND PAYMENT/EXCHANGE OF ANY FEE/MONEY/CHARGES THEREOF. THUS, THE COMPANY, ITS AFFILIATES, OR ANY OF THE FOREGOING'S OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, SUB-CONTRACTORS, REPRESENTATIVES, AGENTS ETC. DISCLAIMS ALL LIABILITY, WARRANTIES AND RESPONSIBILITIES IN RESPECT OF THE PROVISION OF THE SERVICES, TRAINING FACILITIES AND ACCESS PROVIDED BY A FITNESS SERVICE PROVIDER AND THE USE AND PROCUREMENT THEREOF BY THE MEMBER. FURTHER, THE USERS AGREES TO INDEMNIFY THE COMPANY, ITS AFFILIATES, AND/ OR ANY OF THE FOREGOING'S OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, SUB-CONTRACTORS, REPRESENTATIVES, AGENTS ETC. FOR ANY AND ALL LOSSES ARISING IN CONNECTION WITH THE PROVISION OF THE SERVICES, TRAINING FACILITIES AND ACCESS PROVIDED BY A FITNESS SERVICE PROVIDER AND THE USE AND PROCUREMENT THEREOF BY THE MEMBER.</p>

<p>&nbsp;</p>

<p><strong>10.16</strong> THE EXCHANGE OF INFORMATION, PROVISION/AVAILING OF SERVICES, TRANSACTION BY AND BETWEEN THE FITNESS SERVICE PROVIDER AND MEMBER IS DONE AT YOUR SOLE RISK, AND HENCE YOU AGREE THAT THE COMPANY SHALL BE IN NO EVENT LIABLE FOR ANY INJURY, LOSSES, CLAIM, DAMAGE OR ANY SPECIAL, EXEMPLARY, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL DAMAGES OF ANY KIND, WHETHER BASED IN CONTRACT, TORT OR OTHERWISE, WHICH ARISES OUT OF OR IS ANY WAY CONNECTED WITH THE AFORESAID.</p>

<p>&nbsp;</p>

<p><strong>10.17</strong> THE USER SHALL NOT HAVE ANY PLEA, CLAIM OR DEMAND AGAINST THE COMPANY, ITS AFFILIATES, AND THEIR RESPECTIVE OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, SUB-CONTRACTORS AND AGENTS ETC. IN RESPECT OF ANY EXCHANGE OF INFORMATION, PROVISION/AVAILING OF SERVICES, TRANSACTION BY AND BETWEEN THE FITNESS SERVICE PROVIDER AND MEMBER. THE COMPANY WILL NOT BE DEEMED THE PROVIDER OR RECIPIENT OF ANY SERVICES ACQUIRED THROUGH BY A USER THROUGH THE ELECTRONIC MEDIA OR PURSUANT TO REGISTRATION OF A PERSON AS A USER WITH THE COMPANY AND THE ELECTRONIC MEDIA.</p>

<p>&nbsp;</p>

<p><strong>10.18</strong> ANY SEPARATE AND INDEPENDENT ARRANGEMENT/AGREEMENT ENTERED INTO BETWEEN USERS WHICH IS BEYOND THE SCOPE OF THE SERVICES AND PRODUCTS OF THE COMPANY SERVICES WITH REGARD TO THE PROVISION OF SERVICE BY A FITNESS SERVICE PROVIDER AND THE USE OF THE FACILITIES, SERVICES AND ACCESS PROVIDED BY THE MEMBER, THE SAME WILL CONSTITUTE A STANDALONE AND INDEPENDENT AGREEMENT BETWEEN THE MEMBER AND THE MEMBER, AND SUCH USERS WILL BE SOLELY RESPONSIBLE FOR SUCH AGREEMENT MADE WITH THE OTHER USER. IT IS CLARIFIED THAT THE COMPANY WILL NOT BE LIABLE FOR ENFORCING ANY SUCH AGREEMENT THAT WAS MADE BETWEEN SUCH USERS. IN THE EVENT OF A DISPUTE BETWEEN THE FITNESS SERVICE PROVIDER AND THE MEMBER REGARDING ANY TRANSACTION CONDUCTED VIA THE ELECTRONIC MEDIA, BOTH THE USERS HEREBY RELIEVES THE COMPANY, ITS AFFILIATES, THEIR RESPECTIVE OFFICERS, DIRECTORS, SHAREHOLDERS, EMPLOYEES, SUB-CONTRACTORS AND AGENTS FROM ALL MANNER OF ACTIONS, CLAIMS OR DEMANDS AND FROM ANY AND ALL LOSSES (DIRECT, INDIRECT, INCIDENTAL OR CONSEQUENTIAL), DAMAGES, COSTS OR EXPENSES, INCLUDING, WITHOUT LIMITATION, COURT COSTS AND ATTORNEYS' FEES, WHICH A USER MAY HAVE AGAINST THE OTHER.</p>

<p>&nbsp;</p>

<p><strong>10.19</strong> THE USERS EXPRESSLY UNDERSTANDS AND AGREES THAT THE COMPANY DISCLAIMS ANY LIABILITY WITH RESPECT TO ANY CLAIM, SUIT OR ACTION BROUGHT BY THE MEMBER OR ANY THIRD PARTY IN RELATION TO ANY USE OF/AVAILING OF THE SERVICES AND PRODUCTS OFFERED/PROVIDED BY THE FITNESS SERVICE PROVIDER; AND THE FITNESS SERVICE PROVIDER AGREES TO INDEMNIFY, DEFEND AND HOLD THE COMPANY HARMLESS IN CONNECTION WITH ANY SUCH CLAIM.</p>

<p>&nbsp;</p>

<p><strong>10.20</strong> THE USERS EXPRESSLY UNDERSTANDS AND AGREES THAT THE COMPANY DISCLAIMS ANY LIABILITY WITH RESPECT TO ANY CLAIM, SUIT OR ACTION BROUGHT BY A FITNESS SERVICE PROVIDER IN CONNECTION WITH PAYMENT FOR SERVICES BY THE MEMBER AND THE MEMBER AGREES TO INDEMNIFY, DEFEND AND HOLD THE COMPANY HARMLESS IN CONNECTION WITH ANY SUCH CLAIM.</p>

<p>&nbsp;</p>

<p><strong>10.21</strong> THE AFORESAID, DISCLAIMERS, WAIVERS, RELEASES, LIMITATIONS AND EXCLUSIONS WILL APPLY REGARDLESS OF WHETHER THE CAUSE OF ACTION OR THE LIABILITY ARISES IN LAWS, CONTRACT, TORT OR OTHERWISE.</p>

<p style="margin-left:80px;">&nbsp;</p>

<p>&nbsp;</p>

<p><strong>11. <u>Limitation of Liability</u></strong></p>

<p>&nbsp;</p>

<p><strong>11.1</strong> The User expressly understands and agrees that the Company, its affiliates, and any of the its officers, directors, shareholders, employees, sub-contractors agents etc. will not be liable for any indirect, incidental, special, punitive, exemplary or consequential damages (including, without limitation, damages for interruption of services, loss of business, loss of profits, loss of revenue, loss of data, or loss or increased expense of use or any third party incurs), whether in an action in contract, warranty, tort (including, without limitation, negligence).</p>

<p>&nbsp;</p>

<p><strong>11.2</strong> The User further expressly understands and agrees that the Company disclaims any liability with respect to any claim, suit or action brought by User or any third party in relation to any use of and access to the facility, services, schemes, offers provided/granted by the Fitness Service Provider.</p>

<p>&nbsp;</p>

<p><strong>11.3</strong> The Company shall also not assume liability for any errors or omissions in any content, or for any loss or damage of any kind incurred as a result of the use of any content/material posted or uploaded on the Electronic Media by you, or any infringement of another's rights, including intellectual property rights. You specifically agree that the Company is not responsible for any content sent using and/or included in the Company’s Website or other Electronic Media by any third party (including the Users).</p>

<p>&nbsp;</p>

<p><strong>11.4</strong> The User expressly understands and agrees that the Company, its affiliates, and any of its officers, directors, shareholders, employees, sub-contractors agents etc. shall not be liable to the User or any third party for any Losses and/or any other direct, indirect, incidental, consequential, special, punitive or exemplary damages (including, but not limited to, loss of business, revenue, profits, use, data or other economic advantage) arising out of or in connection with <strong>(i)</strong> the use or the inability to use the Electronic Media and Company’s products and/or services; <strong>(ii)</strong> services/transactions/interactions/exchange of information made resulting from the use of the platform, products, data, information or obtained or messages receive through or from the Electronic Media and the Services (including any services/transactions/interactions/exchange of information made between the Fitness Service Provider and Member and payments of fee thereof); <strong>(iii)</strong> unauthorized access to or alteration of transmissions or data; or<strong> (iv)</strong> any other matters relating to the Electronic Media and the Company’s products and/or services.</p>

<p>&nbsp;</p>

<p><strong>11.5</strong> The maximum aggregate liability of the Company under or in relation to the T&amp;C and any other relevant Company Policy and any Losses arising therefrom; will not exceed and will be capped at total payments made to the Company by a User in the immediately preceding 1 (one) month or any other amount specified in the relevant Company Policy applicable to the Service of the Company which the User avails or Rs. 2500, whichever is higher. In the event applicable law does not allow the limitation of liability as set forth above, the limitation will be deemed modified solely to the extent necessary to comply with applicable law.</p>

<p>&nbsp;</p>

<p><strong>11.6</strong> Under no circumstances shall the Company be held responsible or liable, in any way, for any conduct of the Member at the premises of the Fitness Service Provider or uploading of any content by a Member on the Electronic Media or any other electric or print media/platform, including any publishing of any content which, in legal opinion, is derogatory, threatening, defamatory, obscene or offensive or offends public sensibilities or morals.</p>

<p style="margin-left:80px;">&nbsp;</p>

<p>&nbsp;</p>

<p><strong>12. <u>Indemnification</u></strong></p>

<p>&nbsp;</p>

<p>In addition and not in derogation of the specific indemnities provide by the Users to the Company under theses T&amp;C and/or the Company Polices, you agree to indemnify, defend and hold harmless the Company, and its affiliates, officers, directors, employees, consultants, representatives, shareholders, contractors, users and agents etc. against any and all Losses arising out of or in connection with any claim, suit, action, or other proceeding brought against the Company or such party, to the extent such Losses are based on or arising out of or in connection with: <strong>(a)</strong> any breach of any representation, warranty, covenant or agreement to be performed by the User accordance to the T&amp;C and Company Policies; <strong>(b)</strong> the Fitness Service Providers provision of services to any third party, regardless of whether or not they are user/members of the Company; or <strong>(c)</strong> any materials provided by the Users to the Company/Electronic Media or other Users or and/or any content posted by the User on the Electronic Media otherwise provided to other Users; <strong>(d)</strong> User's refusal to pay for services provided by any Member; <strong>(e) </strong>User's use of the Service and Electronic Media.</p>

<p style="margin-left:40px;">&nbsp;</p>

<p>&nbsp;</p>

<p><strong>13. <u>Proprietary Information and Intellectual Property Rights</u></strong></p>

<p>&nbsp;</p>

<p><strong>13.1</strong> You acknowledge and agree that we and/or our affiliates or licensors or suppliers own all the intellectual property rights in and relating to the Electronic Media, the Services and A2z. Your use of the Electronic Media and/or Services grants you no rights in relation to our or our affiliates or licensor’s or suppliers intellectual property rights. By accessing the Electronic Media and using the Services you also agree to be bound by our Company Policies.</p>

<p>&nbsp;</p>

<p><strong>13.2</strong> You acknowledge and agree that the Services and any necessary software used in connection with the Services contain proprietary and confidential information of the Company that is protected by applicable intellectual property, information technology and other laws. You further acknowledge and agree that the general layout, content and design of the Electronic Media and the Service is protected by copyrights, trademarks, service marks, patents or other proprietary rights and laws. The Electronic Media structure shall not be reproduced, distributed or published, in whole or in part, by you for any purpose without the prior express consent of the Company.</p>

<p>&nbsp;</p>

<p><strong>13.3</strong> Without generality for the aforementioned provision, it is further acknowledged and agreed by you that copyright and all intellectual property rights in all material presented on the Electronic Media, including but not limited to text, audio, video or graphical images, interfaces, graphics, design, compilation, information, computer code, products, software, downloadable software, trademarks, logos and all other material appearing on this Electronic Media (“<strong>Materials</strong>”) are the property of the Company, its parent, affiliates and associates and are protected under applicable Indian laws.</p>

<p>&nbsp;</p>

<p><strong>13.4</strong> Other than in connection with your private use of our Electronic Media or Services, you shall not copy, reproduce, download, publish, adapt, create derivative works, re-publish, post, broadcast, record, print, commercially exploit, transmit, edit, communicate to the public or distribute in any other way, any Material, or content in relation to the Electronic Media and the Services or the computer codes or elements which comprise the Electronic Media and/or the Services.</p>

<p>&nbsp;</p>

<p><strong>13.5</strong> You agree not to use any framing techniques to enclose any trademark or logo or other proprietary information of the Company; or remove, conceal or obliterate any copyright or other proprietary notice on other mark or source identifier included on the Electronic Media/ Service, including without limitation, the size, color, location or style of all proprietary marks. Any infringement shall be vigorously defended and pursued to the fullest extent permitted by law.</p>

<p>&nbsp;</p>

<p><strong>13.6</strong> This T&amp;C does not grant to you any rights to patents, copyrights, trade secrets, trade names, trademarks (whether registered or unregistered), domain names or any other rights, functions or licenses in respect of the Electronic Media; or any Material or information appearing on the Electronic Media; or any services offered by the Company an/or through the Electronic Media. The User cannot create any derivative work or technology based upon any trade secret, intellectual property, confidential or proprietary information of the Company or its licensors.</p>

<p>&nbsp;</p>

<p><strong>13.7</strong> The User cannot adapt or use any trademark, service mark, trade name, logo or domain name similar to or likely to be confused with those of the Company or its licensors, or take any other action that infringes upon or impairs the Company's trademark (whether registered or unregistered) or other intellectual property rights.&nbsp;</p>

<p>&nbsp;</p>

<p><strong>13.8</strong> Other than as set out in this clause and the Company Policies, you are not permitted to use any of our intellectual property rights without our (and our affiliates, licensor’s or suppliers) prior written consent.</p>

<p style="margin-left:80px;">&nbsp;</p>

<p>&nbsp;</p>

<p>&nbsp;</p>

<p><strong>14. <u>Material Posted and Usage of data on Website</u></strong></p>

<p>&nbsp;</p>

<p><strong>14.1</strong> All information, images, documents, codes, data, text, software, music, sound, photographs, graphics, video, messages or other materials (“<strong>Content</strong>”), whether publicly or privately transmitted/posted, is the sole responsibility of the person from where such content is originated. By posting any Content in whole or in part, you represent and warrant that:</p>

<p><strong>(i)</strong> you own, or have the necessary licenses, rights, consents, and permissions to use and authorize/sub-license the Company to use all patent, trademark, copyright, or other proprietary rights in and to the Content posted by you, to enable inclusion and use of your Content in the manner contemplated by the Company, and to grant the rights and license set forth above; and</p>

<p><strong>(ii)</strong> your Content, the Company’s or any Company’s Licensee’s use of such Content pursuant to these T&amp;C and other Company Policies, and exercise of the license rights set forth above, do not and will not <strong>(a)</strong> infringe, violate, or misappropriate any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right; <strong>(b)</strong> cause injury or damage to any other person; <strong>(c)</strong> violate these T&amp;C and other Company Policies or any applicable law or regulation; or <strong>(d)</strong> require obtaining a license from or paying fees or royalties to any third party for the exercise of any rights granted in these T&amp;C and other Company Policies.</p>

<p>&nbsp;</p>

<p><strong>14.2</strong> You represent that you have valid rights and title in any and all Content that you submit on the Electronic Media, that you have not infringed on any intellectual property/proprietary rights of any party and further that you will indemnify the Company and its directors, employees, agents, representatives, contractors, affiliates etc. for all claims and Losses arising out of any content that you post on the Electronic Media or the Company’s product’s site or other electronic platform. You may not send, submit, post, or otherwise transmit, a material or Content that contain software virus, or any other files that are designed to interrupt, destroy, and negatively affect in any manner whatsoever, any electronic equipment in connection with the use of the Electronic Media.</p>

<p>&nbsp;</p>

<p><strong>14.3</strong> The Company accepts no responsibility for the said Content. However, you understand that for the Content posted by you on the Electronic Media of the Company, you will grant/assign to the Company, a non-exclusive, royalty fee, perpetual, irrevocable and sub-licenseable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display such Content (in whole or part) worldwide and/or to incorporate it in other works in any form, media, or technology now known or later developed throughout the world. The Company reserves the right, in its sole discretion, to refuse to allow, edit or remove any Content being posted on the Electronic Media by you or ant third party, at any time with or without notice.</p>

<p>&nbsp;</p>

<p><strong>14.4</strong> Any Content and/ or comment uploaded by you shall be subject to the applicable laws. Furthermore, if you are found to be in non-compliance with the laws and regulations, these T&amp;C, or other Company Policies, the Company shall have the right to immediately terminate/block/suspend your access and usage of the Electronic Media and the Company shall have the right to immediately remove any such non-compliant Content and/or comment, uploaded by you and shall further have the right to take recourse to such remedies as would be available to the Company under the applicable laws.</p>

<p>&nbsp;</p>

<p><strong>14.5</strong> The Company grants you permission to only access and make personal use of the Electronic Media and you agree not to, directly or indirectly, download or modify / alter / change / amend / vary / transform / revise / translate / copy / publish / distribute or otherwise disseminate any content on the Electronic Media and Services, or any portion of it; or delete or fail to display any promotional taglines included in the Electronic Media and Services, either directly or indirectly, except with the express consent of the Company. However, you may print or download extracts from these pages for your personal/individual and non-commercial use only. You must not retain any copies of these pages saved to disk or to any other storage medium except for the purposes of using the same for subsequent viewing purposes or to print extracts for personal/individual use. The Company forbids you from any attempts to resell or put to commercial use any part of the Electronic Media and Services; any collection and use of any product listings, descriptions, offers, or prices; any derivative use of the Electronic Media and Services or its contents; any downloading or copying of account information for the benefit of any third party; any assignment, leasing, or otherwise transferring rights to the Electronic Media and the Services; displaying the name, logo, trademark or other identifier of another person in such a manner as to give the viewer the impression that such other person is a publisher or distributor of the services on the Electronic Media, products offered by the Company or any data gathering or extraction tools; or any use of meta tags. You may not (whether directly or through the use of any software program) create a database in electronic or structured manual form by regularly or systematically downloading and storing all or any part of the pages from the Electronic Media and Services. No part of the Electronic Media and Services may be reproduced or transmitted to or stored in any other website, nor may any of its pages or part thereof be disseminated in any electronic or non-electronic form, nor included in any public or private electronic retrieval system or service, without prior written permission.</p>

<p style="margin-left:80px;">&nbsp;</p>

<p>&nbsp;</p>

<p><strong>15. </strong><u><strong>Confidential Information</strong></u></p>

<p>&nbsp;</p>

<p><strong>15.1</strong> Subject to the Privacy Policy, each party agrees that all know-how, business, technical and financial information it obtains, receives, has access to (“<strong>Receiving Party</strong>”) from the disclosing party (“<strong>Disclosing Party</strong>”), including but not limited to the that the Services, Materials, intellectual property or proprietary information of the Company, the scheme and terms of the arrangement contemplated under the T&amp;C and any terms relating to a particular service/product offered by the Company, pricing information, information about its customers, marketing and promotions, business plans etc., are proprietary and confidential information of the Company (“<strong>Confidential Information</strong>”). Except as otherwise required by applicable laws or by judicial/quasi-judicial authorities/governmental agencies, the Receiving Party agrees that it shall not disclose such Confidential Information to any third party without the written and prior consent of the Disclosing Party.</p>

<p>&nbsp;</p>

<p><strong>15.2</strong> Except as otherwise provided in the Privacy Policy, the Parties may, (subject to prior written intimation to the other Party) on a ‘need to know basis’ for the purposes contemplated by these T&amp;C disclose confidential information to its directors, employees and professional advisors including auditors, bankers and lawyers, provided each of such person is bound by similar obligations of confidentially as set out herein. Provided however that insofar as such disclosure is reasonably necessary to such Receiving Party's employees, consultants, directors or professional advisers, provided that such Receiving Party shall make reasonable efforts to ensure (excluding the need to take any legal action) that such employees, consultants, directors or professional advisors treat such information as confidential, and such Receiving Party will be responsible for breach of the confidentiality obligations by such affiliates, employees, consultants, directors or professional advisors irrespective of whether such Receiving Party has entered into similar confidentiality agreement with such persons.</p>

<p style="margin-left:80px;">&nbsp;</p>

<p>&nbsp;</p>

<p><strong>16. <u>Advisements and Links</u></strong></p>

<p>&nbsp;</p>

<p><strong>16.1</strong> The Company may include on the Electronic Media, advertisements on its own behalf or paid advertisements on behalf of third parties. By clicking on the advertisements, the User may be redirected to a website or other electronic platform of the advertiser or receive other messages, information or offers from the advertiser. The User acknowledges and agrees that the Company is not liable or responsible for the content, products or services of such advertisers or the websites, links, information, messages, offers or privacy practices of such advertisers. The User is wholly liable for all communications and transactions with advertisers.</p>

<p>&nbsp;</p>

<p><strong>16.2</strong> The Electronic Media may contain links or other content related to websites, products and/or services offered by third parties. The Company has no control over any content, websites, products or services or any information provided or transmitted via such links, websites, products or services, or otherwise provided by any such third party. The User acknowledges and agrees that the Company is not responsible for the availability of such third party links, content, websites, products or services and will not be responsible or liable for any content, advertising, products or other materials contained therein or the business practices or privacy practices related thereto. The User warrants and agrees that the Company will not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such link, website, content, product and/or service.</p>

<p style="margin-left:80px;">&nbsp;</p>

<p>&nbsp;</p>

<p><strong>17. <u>No Controlling Spam Policy or Unsolicited E-mails</u></strong></p>

<p>&nbsp;</p>

<p>You will not use any communication tool or other means available on the electronic platform to transmit, directly or indirectly, any unsolicited bulk communications (including emails and instant messages). You may not harvest information about users of the Company, its Website, Electronic Media and other products of the Company for the purpose of sending or to facilitate the sending of unsolicited bulk communications. We may terminate your access or use of the service immediately, with or without any notice, and take any other legal action if you, or anyone using your access details to the Electronic Media, violates these T&amp;C and the Company Policies. We may adopt any technical remedy (including any filtering technology or other measures) to prevent unsolicited bulk communications from entering, utilizing or remaining within our computer or communication networks. Such filtering technology or other measures may block, either temporarily or permanently, some e-mail sent to you through the Company’s Websites and Electronic Media.</p>

<p style="margin-left:80px;">&nbsp;</p>

<p>&nbsp;</p>

<p><strong>18. <u>Suspension and Termination</u></strong></p>

<p>&nbsp;</p>

<p><strong>18.1</strong> You agree that the Company, in its sole discretion and for any or no reason, may terminate the account (or any part thereof) you may have with the Company or use of the Electronic Media and remove and discard all or any part of your account or any content uploaded by you, at any time. The Company may also in its sole discretion and at any time discontinue providing access to the Electronic Media, or any part thereof, with or without notice. You agree that any termination of your access to the Electronica Media or any account you may have or portion thereof, may be effected without prior notice, and you agree that the Company will not be liable to you or any third party for any such termination.</p>

<p>&nbsp;</p>

<p><strong>18.2</strong> In addition to the reasons and the grounds of termination expressly provided for in these T&amp;C above, the Company, in its sole discretion, reserves the right to terminate any account (or any part thereof) or deny access to any account or use of the Service or remove and discard any content within the Service, for any reason, including, without limitation:</p>

<p><strong>(a)</strong> for lack of use of the account; or</p>

<p><strong>(b)</strong> registration of any account using false or misleading information; or</p>

<p><strong>(c)</strong> violation or inconsistent acts with the letter or spirit of the T&amp;C; or</p>

<p><strong>(d)</strong> violation of any applicable laws.</p>

<p>&nbsp;</p>

<p><strong>18.3</strong> You acknowledge and agree that the Company may immediately deactivate or delete your account and all related information and files in your account and/or bar any further access to such files or the Service. Further, you agree that the Company shall not be liable to you or any third-party for any termination of your account or denial of access to the Service. In the event of termination of your account by the Company due to any of the aforementioned reasons, the Company shall have the sole discretion to terminate or cancel any of your past acts without any liability to the Company.</p>

<p>&nbsp;</p>

<p><strong>18.4</strong> The Company does not permit copyright infringing activities on the Electronic Media and reserves the right to terminate access to the Electronic Media and remove all content submitted by any persons who are found to be infringers. Any suspected fraudulent, abusive, or illegal activity that may be grounds for termination of your use of the Electronic Media may be referred to appropriate law enforcement authorities. These remedies are in addition to any other remedies the Company may have under law, contract and/or equity.</p>

<p>&nbsp;</p>

<p><strong>18.5</strong> You may, by giving a written notice to us at the following link [●], terminate or deactivate your account at any time and/or remove any data or files uploaded by you on the account or request us to do the same. Provided that such deactivation or termination either by you or by us will not prejudice any of your past lawful acts on the Electronic Media.</p>

<p style="margin-left:80px;">&nbsp;</p>

<p>&nbsp;</p>

<p><strong>19. <u>Dispute Resolution&nbsp;</u></strong></p>

<p><br>
All disputes arising out of or in connection with the T&amp;C shall be attempted to be settled through negotiation between senior management of the Company and the User. If any dispute arising between the parties is not amicably settled within reasonable period of sixty (60) days of the initiation of the aforesaid dispute resolution mechanisms, then, the same shall be resolved by arbitration in accordance with the provisions of the Rules of Arbitration of the Indian Council of Arbitration for the time being in force, which rules shall be deemed to be incorporated by reference in this Clause 19. The dispute shall be referred to one (1) arbitrator to be appointed/ nominated by the Company. The place of arbitration shall be New Delhi. The language of the arbitration will be English. The decision of the arbitrator will be final, binding and incontestable and may be used as a basis for judgment thereon in India or elsewhere. The Company and the User will bear its own costs of the arbitration.</p>

<p>&nbsp;</p>

<p>&nbsp;</p>

<p><strong>20. <u>General Terms</u></strong></p>

<p>&nbsp;</p>

<p><strong>20.1</strong> We are not liable for any infringement of copyright, trademark, patterns and/or any intellectual or proprietary rights of any third party, arising out of contents and/or materials posted on or transmitted through the Electronic Media or items advertised thereon.</p>

<p>&nbsp;</p>

<p><strong>20.2</strong> We shall have no liability to you for any failure and/or delay in performance of Services or any interruption or delay, to access the Electronic Media, if that failure and/or delay is due to reasons or circumstances beyond our reasonable control (and the time for performance of the same shall be and is extended accordingly). However, if we decide to grant you an indulgence on the performance of any obligation under these T&amp;C, such indulgence shall not constitute waiver of any of our rights.</p>

<p>&nbsp;</p>

<p><strong>20.3</strong> These T&amp;C and the Company Policies incorporated herein by reference constitute the entire agreement between the parties with respect to the subject matter hereof and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding such subject matter.</p>

<p>&nbsp;</p>

<p><strong>20.4</strong> The rights and obligations under the T&amp;C which by their nature should survive will remain in full effect after termination or expiration of the T&amp;C.</p>

<p>&nbsp;</p>

<p><strong>20.5</strong> If any provision of the T&amp;C becomes or is declared by a court of competent jurisdiction to be invalid, illegal or unenforceable then such invalidity, illegality or unenforceability shall not affect the validity of the other provisions of the T&amp;C, which shall remain in full force and effect.</p>

<p>&nbsp;</p>

<p><strong>20.6</strong> No representation of our employees, officers or agents or those contained and advertised on the Website or the Electronic Media shall represent an addition or amendment to these T&amp;C unless the same has been set out in writing and signed by one of our directors.</p>

<p>&nbsp;</p>

<p><strong>20.7</strong> You agree not to assign, transfer or novate your rights or obligations under these T&amp;C, without our prior written consent, if applicable.</p>

<p>&nbsp;</p>

<p><strong>20.8</strong> The laws of India will govern these T&amp;C. Subject to Clause 16, by accepting to these T&amp;C you agree to irrevocably submit to the exclusive jurisdiction of the courts at New Delhi in respect of any disputes, acts, matters or controversies arising as a result of breach of these T&amp;C those relating to the validity, enforcement and/or interpretation of the terms of these T&amp;C.</p>

<p>&nbsp;</p>

<p><strong>20.9</strong> Failure on our part to exercise or enforce any right or provision of these T&amp;C shall not constitute a waiver of such right or provision.</p>

<p>&nbsp;</p>

<p><strong>20.10</strong> No partnership, joint venture or relationship of employee/employer or franchisor/franchisee arises between you and us by reason of these T&amp;C.</p>

<p>&nbsp;</p>

<p><strong>20.11</strong> In our discretion we may serve any notice or communication on you by email, or mail. In the case of notices sent by <strong>(a)</strong> fax, you will be deemed served at the time and date of dispatch and receipt of confirmation regarding successful transmission of the fax; <strong>(b)</strong> email, you will be deemed served at the time and date of receipt of such email by you; and <strong>(c)</strong> mail, you will be deemed served 5 (five) business days after dispatch of the same.</p>

<p>&nbsp;</p>

<p><strong>20.12</strong> No person other than you has any rights under these T&amp;C and cannot enforce these T&amp;C.</p>

<p>&nbsp;</p>

<p><strong>20.13</strong> As part of the registration process you agree to receive such marketing and promotional materials via mail, sms, email and/or fax as we may deem appropriate to send you in connection with our Website and Services. For further details relating to the same, please refer to our Privacy Policy.</p>

<p style="margin-left:80px;">&nbsp;</p>

<p>&nbsp;</p>

<p><strong>21. <u>...............</u></strong></p>

<p>&nbsp;</p>

<p>Any complaints, abuse or concerns with regards to content and or comment or breach of these T&amp;C shall be immediately informed to Mr. ..... ("<strong></strong>") through email at a2zgym.com&nbsp;with the electronic signature or in writing at the following address to:</p>

<p style="text-align:center;"><br><strong>Attn : Mr. </strong></p>

<p style="text-align:center;"><strong>Designation :</strong></p>

<p style="text-align:center;"><strong>Corporate Address : </strong></p>

<p>&nbsp;</p>
  </div>  
</div> 
 















</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ScriptSecton" runat="server">
</asp:Content>
